name: Feature request
description: Suggest an idea for Coreflux
title: "[Feature]: "
labels: ["community_new", "feature_request"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        **Thanks for taking the time to fill out our feature request form! We appreciate your input and will respond as soon as we can.**

  - type: textarea
    id: feature-description
    attributes:
      label: "Tell us about your request"
      description: "What feature or improvement would you like to see in Coreflux?"
      placeholder: "I would like..."
    validations:
      required: true

  - type: checkboxes
    id: component
    attributes:
      label: "Which component(s) is this request for?"
      description: "Please specify which area(s) of Coreflux you want this feature for."
      options:
        - label: "Coreflux Broker"
        - label: "Coreflux Hub"
        - label: "Flux Assets"
        - label: "Flux Language"
        - label: "Power Ups"
        - label: "User Experience (UX)"
        - label: "Documentation"
        - label: "Conceptual Features"
    validations:
      required: true

  - type: textarea
    id: problem-description
    attributes:
      label: "Is your feature request related to a problem? Please describe."
      description: "A clear and concise description of what the problem is."
      placeholder: "I'm always frustrated when..."
    validations:
      required: false

  - type: textarea
    id: solution-description
    attributes:
      label: "Describe the solution you'd like"
      description: "A clear and concise description of what you want to happen."
      placeholder: "I would like..."
    validations:
      required: true

  - type: textarea
    id: alternatives-description
    attributes:
      label: "Describe alternatives you've considered"
      description: "A clear and concise description of any alternative solutions or features you've considered."
      placeholder: "I have considered..."
    validations:
      required: false

  - type: textarea
    id: new-asset-description
    attributes:
      label: "Is this request for a new asset?"
      description: "If you're suggesting a new asset such as a connector or aggregator, please describe its functionality and potential use cases."
      placeholder: "I am suggesting a new asset that..."
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: "Additional context"
      description: "Add any other context, screenshots, or diagrams about the feature request here."
      placeholder: "Additional details..."
    validations:
      required: false
